In [7]:
import numpy as np
from os import

a = np.random.random((3,4))
print(a)
a.ravel()
a.reshape(6,2)
a.T
np.set_printoptions(threshold=sys.maxsize)
c = np.array([[[1,2,3],
              [8, 9, 10]],
             [[100,101,102],
             [111,112,113]]])
print(c)
print(c.shape)
print(c[1,...])
print(c[...,2])

[[0.76216428 0.26528053 0.20227599 0.6383298 ]
 [0.65112948 0.16447836 0.08139597 0.05045134]
 [0.05862051 0.38464944 0.70409801 0.26635428]]
[[[  1   2   3]
  [  8   9  10]]

 [[100 101 102]
  [111 112 113]]]
(2, 2, 3)
[[100 101 102]
 [111 112 113]]
[[  3  10]
 [102 113]]


In [6]:
import numpy as np
import matplotlib.osplot as plt


def mandelbrot(h, w, maxit=20):
    """Returns an image of the Mandelbrot fractal of size (h,w)."""
    y, x = np.ogrid[-1.4:1.4:h*1j, -2:0.8:w*1j]
    c = x+y*1j
    z = c
    divtime = maxit + np.zeros(z.shape, dtype=int)
    for i in range(maxit):
        z = z**2 + c
        diverge = z*np.conj(z) > 2**2            # who is diverging
        div_now = diverge & (divtime == maxit)  # who is diverging now
        divtime[div_now] = i                  # note when
        z[diverge] = 2                        # avoid diverging too much
    return divtime


plt.imshow(mandelbrot(400, 400))
plt.show()

ModuleNotFoundError: No module named 'matplotlib.osplot'

In [3]:
import numpy as np


c = np.array([[1,2], [3,4]], dtype=complex)
com = 1+2*1j
np.conj(com)
print(com)

(1+2j)


In [1]:
%load_ext sql

In [7]:
!pip install openpyxl

     |████████████████████████████████| 243 kB 1.8 MB/s eta 0:00:01


In [11]:
import os
import pandas as pd


os.chdir('/Users/phuoc/Downloads')
df = pd.read_excel('KVLHCM.xlsx')
df.dtypes

STT                        object
Ngày vận đơn               object
Số vận đơn                 object
Từ tỉnh                    object
Đến tỉnh                   object
Từ huyện                   object
Đến huyện                  object
Đến xã                     object
Tên người gửi              object
HTTT                       object
Địa chỉ người gửi          object
SDT người nhận             object
Tên người nhận             object
Địa chỉ người nhận         object
Tên DV                     object
Mã DV                     float64
Mã KH                     float64
Trọng lượng               float64
Số kiện                   float64
Trọng lượng qui đổi       float64
Trọng lượng qui đổi KS    float64
Loại áp giá                object
Tiền cước kiểm soát       float64
Phí KS                    float64
Phí 04                    float64
Tiền cước vận đơn         float64
Phí                       float64
Tên hàng hóa               object
Thời gian trả hàng         object
Người nhận    

In [16]:
df['Số tham chiếu']

0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
        ..
6709   NaN
6710   NaN
6711   NaN
6712   NaN
6713   NaN
Name: Số tham chiếu, Length: 6714, dtype: float64