In [7]:
import numpy as np
from os import

a = np.random.random((3,4))
print(a)
a.ravel()
a.reshape(6,2)
a.T
np.set_printoptions(threshold=sys.maxsize)
c = np.array([[[1,2,3],
              [8, 9, 10]],
             [[100,101,102],
             [111,112,113]]])
print(c)
print(c.shape)
print(c[1,...])
print(c[...,2])

[[0.76216428 0.26528053 0.20227599 0.6383298 ]
 [0.65112948 0.16447836 0.08139597 0.05045134]
 [0.05862051 0.38464944 0.70409801 0.26635428]]
[[[  1   2   3]
  [  8   9  10]]

 [[100 101 102]
  [111 112 113]]]
(2, 2, 3)
[[100 101 102]
 [111 112 113]]
[[  3  10]
 [102 113]]


In [6]:
import numpy as np
import matplotlib.osplot as plt


def mandelbrot(h, w, maxit=20):
    """Returns an image of the Mandelbrot fractal of size (h,w)."""
    y, x = np.ogrid[-1.4:1.4:h*1j, -2:0.8:w*1j]
    c = x+y*1j
    z = c
    divtime = maxit + np.zeros(z.shape, dtype=int)
    for i in range(maxit):
        z = z**2 + c
        diverge = z*np.conj(z) > 2**2            # who is diverging
        div_now = diverge & (divtime == maxit)  # who is diverging now
        divtime[div_now] = i                  # note when
        z[diverge] = 2                        # avoid diverging too much
    return divtime


plt.imshow(mandelbrot(400, 400))
plt.show()

ModuleNotFoundError: No module named 'matplotlib.osplot'

In [3]:
import numpy as np


c = np.array([[1,2], [3,4]], dtype=complex)
com = 1+2*1j
np.conj(com)
print(com)

(1+2j)


In [4]:
!conda --version

conda 4.8.3


In [ ]:
!python -c "dir(numpy)"

In [2]:
!pip list

Ptmux;]4;0;rgb:32/30/2f\033\Ptmux;]4;1;rgb:fb/49/34\033\Ptmux;]4;2;rgb:b8/bb/26\033\Ptmux;]4;3;rgb:fa/bd/2f\033\Ptmux;]4;4;rgb:83/a5/98\033\Ptmux;]4;5;rgb:d3/86/9b\033\Ptmux;]4;6;rgb:8e/c0/7c\033\Ptmux;]4;7;rgb:d5/c4/a1\033\Ptmux;]4;8;rgb:66/5c/54\033\Ptmux;]4;9;rgb:fb/49/34\033\Ptmux;]4;10;rgb:b8/bb/26\033\Ptmux;]4;11;rgb:fa/bd/2f\033\Ptmux;]4;12;rgb:83/a5/98\033\Ptmux;]4;13;rgb:d3/86/9b\033\Ptmux;]4;14;rgb:8e/c0/7c\033\Ptmux;]4;15;rgb:fb/f1/c7\033\Ptmux;]4;16;rgb:fe/80/19\033\Ptmux;]4;17;rgb:d6/5d/0e\033\Ptmux;]4;18;rgb:3c/38/36\033\Ptmux;]4;19;rgb:50/49/45\033\Ptmux;]4;20;rgb:bd/ae/93\033\Ptmux;]4;21;rgb:eb/db/b2\033\Ptmux;]10;rgb:d5/c4/a1\033\Ptmux;]11;rgb:32/30/2f\033\Ptmux;]12;7\033\Package                       Version
----------------------------- -------------------
absl-py                       0.11.0
alembic                       1.4.3
aniso8601       

In [3]:
!conda list

Ptmux;]4;0;rgb:32/30/2f\033\Ptmux;]4;1;rgb:fb/49/34\033\Ptmux;]4;2;rgb:b8/bb/26\033\Ptmux;]4;3;rgb:fa/bd/2f\033\Ptmux;]4;4;rgb:83/a5/98\033\Ptmux;]4;5;rgb:d3/86/9b\033\Ptmux;]4;6;rgb:8e/c0/7c\033\Ptmux;]4;7;rgb:d5/c4/a1\033\Ptmux;]4;8;rgb:66/5c/54\033\Ptmux;]4;9;rgb:fb/49/34\033\Ptmux;]4;10;rgb:b8/bb/26\033\Ptmux;]4;11;rgb:fa/bd/2f\033\Ptmux;]4;12;rgb:83/a5/98\033\Ptmux;]4;13;rgb:d3/86/9b\033\Ptmux;]4;14;rgb:8e/c0/7c\033\Ptmux;]4;15;rgb:fb/f1/c7\033\Ptmux;]4;16;rgb:fe/80/19\033\Ptmux;]4;17;rgb:d6/5d/0e\033\Ptmux;]4;18;rgb:3c/38/36\033\Ptmux;]4;19;rgb:50/49/45\033\Ptmux;]4;20;rgb:bd/ae/93\033\Ptmux;]4;21;rgb:eb/db/b2\033\Ptmux;]10;rgb:d5/c4/a1\033\Ptmux;]11;rgb:32/30/2f\033\Ptmux;]12;7\033\# packages in environment at /Users/phuoc/miniconda3/envs/lab:
#
# Name                    Version                   Build  Channel
absl-py                   0.11.0             

In [1]:
%load_ext sql

Environment variable $DATABASE_URL not set, and no connect string given.
Connection info needed in SQLAlchemy format, example:
               postgresql://username:password@hostname/dbname
               or an existing connection: dict_keys([])
